language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: aRxm1SOoIBPqQALCWYEnwRXfsaBFTzUhzhvKxM2W0qkK0iGo2t+ScTd+6xLR1M2SU2o509x5SO2jpby92b0F/2HHe7LNqN53Yent1Nt/ZRrj/rMicnlQks54f6kWyl0CY/zexLhwHTOk56jJimiZlr447Yx3+WYdjhrkN15NjUUHHIWlxlri2AAXoBkY+T75XyM2konGwXtEAOL1+X9FUbLknH1D3c3SDkThDmn5FkW8hQn8Qp7MCXTFsrO9Q+yVyAqNBG4QNA5LBXrGSe4Iv86s3me73ijOEvnAZnNNHrg8d3SJVZ4Zfr0QgvGTJaFmB6Bedm5IDBQYGlnEBtxNJAsCQYSRtYuRUtMbb74oFX0c7RilewWE8qMtcM8PZgUvqS8UDpOEVmHF2mVIblTTKu4pSa3ZFCWs0Tl2U3pMaedWCFOHcbumghhNXLEHWmXBo2Dil2HQOSXxvMZ0atyA5ZCB1DCBA3BM9S9y6BCP9PycLtBjlzdsqG7rCV8VUxB5KbDdQBxGrh3HhCI99UYjiAi3unIGvoTTnvSW0ExMMom902PyJAUuojIqhXCUylqyCXtHpX6hygx46w6t5hkKFNanm9yOEawcAk+vMo3ODNzEnCWto3RMTT11imuYnCrxf9rYYzulI6cawMFRdT64YXuGXAt6uk3rs2tm0j5tY54=
  app: relationship-note
  on:
    repo: yajamon/relationship-note
